server:
  port: ${PHONEBOOKING_PORT:8080}
  error:
    include-exception: false
    include-stacktrace: never

management:
  endpoints:
    enabled-by-default: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  main.banner-mode: off
  application:
    name: PHONE_BOOKING
  data:
    web:
      pageable:
        default-page-size: 50

  datasource:
    url: jdbc:h2:mem:phonebooking
    username: sa
    password: password
  liquibase:
    change-log: classpath:/db/master.xml

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        ddl-auto: validate
        id:
          new_generator_mappings: false
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        max_fetch_depth: 5
