server:
  port: ${PHONE_BOOKING_PORT:8080}
  error:
    include-exception: true
    include-stacktrace: always

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  h2:
    console.enabled: false
  datasource:
    url: jdbc:h2:./data/phonebooking
    username: sa
    password: password
  liquibase:
    change-log: classpath:/db/master.xml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.EnumType: trace
    org.springframework.transaction.interceptor: TRACE

